query ($userName: String!) {
  user(login: $userName) {
    id
    name
    avatarUrl
    url
    repositories(orderBy: { direction: DESC, field: PUSHED_AT }, last: 100) {
      nodes {
        id
        name
        description
        languages(orderBy: { direction: DESC, field: SIZE }, last: 5) {
          nodes {
            id
            name
            color
          }
        }
        url
        pushedAt
      }
    }
    contributionsCollection {
      contributionCalendar {
        totalContributions
        weeks {
          firstDay
          contributionDays {
            contributionCount
            date
          }
        }
      }
    }
  }
}
